//Defininizione INTERFACCIA per rappresentare un'Activity

//Interface for GET
export interface Activity {
    id: number;
    title: string;
    duration: number;
    date: string;
    categoryId: number;
    createdAt: string;
}

//Interface for POST (id will be generated by the backend)
export interface CreateActivity {
    title: string;
    duration: number;
    date: string;
    categoryId: number;
    createdAt: string;
}

//Interface for PUT
export interface UpdateActivity {
    id: number;
    title?: string;
    duration?: number;
    date?: string;
    categoryId?: number;
}