//Defininizione INTERFACCIA per rappresentare un'Activity
//L'interfaccia Activity definisce la struttura dei dati per un'attività, con proprietà come id, title, duration e categoryId. Questa interfaccia viene utilizzata per tipizzare i dati ricevuti dal backend API e garantire che le attività abbiano una struttura coerente in tutta l'applicazione.

//Interface for GET
export interface Activity {
    id: number;
    title: string;
    duration: number;
    date: Date;
    categoryId: number;
    createdAt: string;
}

//Interface for POST (without id, because it will be generated by the backend)
export interface CreateActivity {
    title: string;
    duration: number;
    date: Date;
    categoryId: number;
    createdAt: string;
}

//Interface for PUT
export interface UpdateActivity {
    id: number;
    title?: string;
    duration?: number;
    date?: Date;
    categoryId?: number;
}

