//Defininizione INTERFACCIA per rappresentare un'Activity

//Interface for GET
export interface Activity {
    id: number;
    title: string;
    duration: number;
    date: string;
    categoryId: number;
    createdAt: string;
}

//Interface for POST (id will be generated by the backend)
export interface ActivityCreate {
    title: string;
    duration: number;
    date: string;
    categoryId: number;
}

//Interface for PUT
export interface ActivityUpdate {
    id: number;
    title: string;
    duration: number;
    date: string;
    categoryId: number;
}